name: spider_water
description: synth rock for debutants
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  url_launcher: ^6.1.5
  intl: ^0.18.1
  flutter_insta: ^1.0.1
  just_audio: ^0.9.34
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  flutter_markdown: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/damn-attempt.gif
    - assets/audio/raining-beat.wav
    - assets/img/stew1.jpg
    - assets/img/stew2.jpg
    - assets/img/stew3.jpg
    - assets/img/stew4.jpg
    - assets/img/dan.png
    - assets/img/emma.png
    - assets/img/stin.png
    - assets/img/chuck.png
    - assets/img/album.jpg
    - assets/img/amazon-music.png
    - assets/img/apple-music.png
    - assets/img/bandcamp.png
    - assets/img/spotify.png
    - assets/img/tidal.png
    - assets/img/youtube-music.png
    - assets/img/youtube.png
    - assets/img/dan-union.jpg
    - assets/img/emma-union.jpg
    - assets/img/stew5.jpg
  fonts:
    - family: Blockstepped
      fonts:
        - asset: fonts/Blockstepped.ttf


